// game/lattice.ts — what you can build, and why you cannot build anything else.
//
// The crafting system is a restriction theorem. That is not a conceit: a
// protein is built from L-amino acids, so it is chiral, so it cannot sit in any
// symmetry operation that would hand it its own mirror image. Of the 32
// crystallographic point groups exactly 11 survive that — the enantiomorphic
// ones, which contain only proper rotations — and src/sohncke.ts is already
// built on the fact. So the recipe list below is not a design decision anyone
// made. It is every cell a chiral world permits, and there are eleven.
//
// HOW A GROUP IS BUILT. Each of the 11 is generated by combining rotation axes,
// and each recipe here is that generation written out:
//
//     an n-fold on the principal axis, alone           ->  1  2  3  4  6
//     ...with a 2-fold across it (a girdle)            ->  222  32  422  622
//     ...with a 3-fold down a body diagonal            ->  23   (from a 2-fold)
//                                                          432  (from a 4-fold)
//
// FIVE IS THE WALL. A 5-fold axis generates no lattice — it cannot tile the
// plane, which is the crystallographic restriction theorem and the oldest hard
// no in the subject. A 5-fold motif in this game therefore never crystallises,
// no matter what it is combined with. It is not a bug to be routed around and
// there is no recipe hidden behind it.
//
// THE TWO STATS ARE IN TENSION, AND THE LIBRARY SETS THE RATE. A cell's
// STRUCTURE is its group order — how many operations hold it together. Its
// FREEDOM is the number of independent piezoelectric components neumann.ts
// finds surviving in it — how many distinct ways a field can drive it. Neumann's
// principle makes these pull against each other exactly: 1 has order 1 and 18
// free components, 432 has order 24 and none at all. Nothing balances that
// curve. It is what a projector onto the invariant subspace does.

import {
  type PointGroup, isPiezoelectric, isPolar, pointGroup,
} from "../src/pointgroups.js";
import { independentComponents } from "../src/neumann.js";
import { groupsOfPointGroup } from "../src/sohncke.js";
import { type Particle } from "../src/gorkov.js";

// ── motifs: the things drifting in the medium ───────────────────────────────

/** Where a motif's rotation axis sits relative to the principal one. */
export type Role = "axial" | "girdle" | "diagonal";

export interface Motif {
  id: string;
  label: string;
  role: Role;
  /** Proper rotation order. 5 is included precisely because it is impossible. */
  order: 1 | 2 | 3 | 4 | 5 | 6;
  /** The particle this motif is, acoustically. Its contrast sign decides
   *  whether you gather it at a node or at an antinode, and its radius decides
   *  whether you can gather it at all. */
  particle: Particle;
  /** One line, shown when it is selected. */
  note: string;
}

const CELLISH = { rho: 1100, c: 1570 };   // denser and stiffer than water: node-seeking
const LIPIDISH = { rho: 915, c: 1450 };   // lighter and softer: antinode-seeking
const LIGHT = { rho: 1050, c: 1520 };

export const MOTIFS: Readonly<Record<string, Motif>> = {
  a1: {
    id: "a1", label: "MONOMER", role: "axial", order: 1,
    particle: { radius: 6.0e-6, ...CELLISH },
    note: "NO SYMMETRY AT ALL. BUILDS THE GROUP THAT ASKS FOR NONE",
  },
  a2: {
    id: "a2", label: "DIMER", role: "axial", order: 2,
    particle: { radius: 7.0e-6, ...CELLISH },
    note: "A TWO-FOLD AXIS. THE COMMONEST THING IN THE MEDIUM",
  },
  a3: {
    id: "a3", label: "TRIMER", role: "axial", order: 3,
    particle: { radius: 6.5e-6, ...CELLISH },
    note: "A THREE-FOLD AXIS",
  },
  a4: {
    id: "a4", label: "TETRAMER", role: "axial", order: 4,
    particle: { radius: 5.0e-6, ...CELLISH },
    note: "A FOUR-FOLD AXIS. SMALLER, SO SLOWER TO GATHER",
  },
  a5: {
    id: "a5", label: "PENTAMER", role: "axial", order: 5,
    particle: { radius: 6.0e-6, ...CELLISH },
    note: "FIVE-FOLD. NO LATTICE WILL EVER TAKE IT",
  },
  a6: {
    id: "a6", label: "HEXAMER", role: "axial", order: 6,
    particle: { radius: 4.0e-6, ...CELLISH },
    note: "A SIX-FOLD AXIS. THE SMALLEST AXIAL, AND THE HARDEST",
  },
  g: {
    id: "g", label: "GIRDLE", role: "girdle", order: 2,
    particle: { radius: 5.5e-6, ...LIPIDISH },
    note: "A TWO-FOLD ACROSS THE AXIS. LIPID-BOUND, SO IT FLEES THE NODE",
  },
  d: {
    id: "d", label: "DIAGONAL", role: "diagonal", order: 3,
    particle: { radius: 1.6e-6, ...LIGHT },
    note: "A THREE-FOLD DOWN A BODY DIAGONAL. TOO SMALL FOR THE FIELD TO HOLD WELL",
  },
};

export function motif(id: string): Motif {
  const m = MOTIFS[id];
  if (!m) throw new Error(`no motif ${id}`);
  return m;
}

// ── the eleven recipes ──────────────────────────────────────────────────────

export interface Recipe {
  /** Motif ids, sorted, that generate the group. */
  parts: readonly string[];
  /** Hermann-Mauguin symbol of what they generate. */
  group: string;
}

/** Every cell a chiral world permits. There is no twelfth. */
export const RECIPES: readonly Recipe[] = [
  { parts: ["a1"], group: "1" },
  { parts: ["a2"], group: "2" },
  { parts: ["a3"], group: "3" },
  { parts: ["a4"], group: "4" },
  { parts: ["a6"], group: "6" },
  { parts: ["a2", "g"], group: "222" },
  { parts: ["a3", "g"], group: "32" },
  { parts: ["a4", "g"], group: "422" },
  { parts: ["a6", "g"], group: "622" },
  { parts: ["a2", "d"], group: "23" },
  { parts: ["a4", "d"], group: "432" },
];

const key = (ids: readonly string[]): string => [...new Set(ids)].sort().join("+");
const BY_PARTS = new Map(RECIPES.map((r) => [key(r.parts), r]));

/** How many motifs must be gathered before a matching set is a crystal rather
 *  than a handful of molecules. A unit cell is not a crystal. */
export const SEED_MASS = 4;

/** Why a set of motifs did not become a cell. */
export type Refusal =
  | "five-fold"       // the crystallographic restriction theorem
  | "two-axes"        // two different principal axes cannot both be principal
  | "no-axis"         // a girdle or a diagonal with nothing to be across
  | "unknown";        // a combination no chiral group is generated by

export interface Assembly {
  /** Every motif in the cluster, including repeats. */
  parts: string[];
  /** The distinct motifs, which are what select the recipe. */
  distinct: string[];
  /** How many motifs are gathered. Mass, not variety. */
  mass: number;
  /** The group these motifs generate, or null if they generate nothing. */
  group: string | null;
  refusal: Refusal | null;
  /** The distinct set is a proper subset of some recipe: worth carrying on. */
  partial: boolean;
  /** Enough of them, and the right ones. This is a cell. */
  crystallises: boolean;
}

/**
 * What a pile of motifs is.
 *
 * Answers four questions at once because the game asks all four every frame: is
 * this a cell yet, could it still become one, has it enough mass, and if it is
 * refused then why exactly. The last matters most — a crafting system that only
 * says NO teaches nothing, and every refusal below has a reason a
 * crystallographer would actually give.
 *
 * VARIETY SELECTS THE GROUP, MASS DECIDES WHETHER IT CRYSTALLISES. One dimer is
 * a molecule with a two-fold axis; four of them stacked on that axis are a
 * crystal of group 2. Adding a fifth changes nothing about which group it is,
 * which is why the recipe is keyed on the distinct set alone.
 */
export function assemble(parts: readonly string[], seed = SEED_MASS): Assembly {
  const all = [...parts].sort();
  const distinct = [...new Set(all)].sort();
  const ms = distinct.map(motif);

  const hit = BY_PARTS.get(key(distinct));
  const enough = all.length >= seed;
  if (hit) {
    return {
      parts: all, distinct, mass: all.length,
      group: hit.group, refusal: null, partial: !enough,
      crystallises: enough,
    };
  }

  const axials = ms.filter((m) => m.role === "axial");
  const partial = RECIPES.some((r) =>
    distinct.length < r.parts.length && distinct.every((id) => r.parts.includes(id)));

  let refusal: Refusal = "unknown";
  if (ms.some((m) => m.order === 5)) refusal = "five-fold";
  else if (axials.length > 1) refusal = "two-axes";
  else if (axials.length === 0 && ms.length > 0) refusal = "no-axis";

  // A five-fold is never partial: nothing it joins can rescue it.
  const fiveFold = ms.some((m) => m.order === 5);
  return {
    parts: all, distinct, mass: all.length,
    group: null,
    refusal: partial && !fiveFold ? null : refusal,
    partial: partial && !fiveFold,
    crystallises: false,
  };
}

/** Whether two clusters are allowed to merge at all. Refused pairs bounce, and
 *  the refusal is what the player is told. */
export function canMerge(a: readonly string[], b: readonly string[]): Assembly {
  return assemble([...a, ...b]);
}

export const REFUSAL_TEXT: Readonly<Record<Refusal, string>> = {
  "five-fold": "FIVE-FOLD. NO LATTICE TAKES IT",
  "two-axes": "TWO PRINCIPAL AXES. ONLY ONE CAN BE",
  "no-axis": "NOTHING FOR IT TO BE ACROSS",
  "unknown": "NO CHIRAL GROUP IS GENERATED BY THIS",
};

// ── what a cell then is ─────────────────────────────────────────────────────

/** What a cell can be used for. Read off the group, never assigned by hand. */
export type Ability = "thrust" | "weave" | "anchor";

export interface Cell {
  group: PointGroup;
  /** Group order: how many operations hold it together. */
  structure: number;
  /** Independent piezoelectric components: how many ways a field can drive it. */
  freedom: number;
  /** How many Sohncke space groups realise this point group — how many
   *  distinct crystals it could actually be. Flavour, and true. */
  variants: number;
  ability: Ability;
  /** Shown in the inventory. */
  blurb: string;
}

/**
 * The cell a group makes.
 *
 * Every field here is computed. `ability` in particular is not a table of
 * game-design choices — it is three predicates out of pointgroups.ts asked in
 * order, and the interesting one is last: 432 is the single group that is
 * non-centrosymmetric and still not piezoelectric, so it is the single cell
 * with no drivable coefficient at all. gorkov's neighbours call that a famous
 * edge case. Here it is the endgame item.
 */
export function cellFor(hm: string): Cell {
  const g = pointGroup(hm);
  const freedom = independentComponents(hm, "piezoelectric");
  const ability: Ability = isPolar(g) ? "thrust" : isPiezoelectric(g) ? "weave" : "anchor";
  return {
    group: g,
    structure: g.order,
    freedom,
    variants: groupsOfPointGroup(hm).length,
    ability,
    blurb: BLURB[ability],
  };
}

const BLURB: Readonly<Record<Ability, string>> = {
  thrust:
    "POLAR: ONE DIRECTION SURVIVES EVERY OPERATION, SO IT CAN PUSH ALONG IT",
  weave:
    "PIEZOELECTRIC BUT NOT POLAR: IT TURNS YOUR PRESSURE INTO STRUCTURE",
  anchor:
    "ORDER 24 AND NOT ONE DRIVABLE COMPONENT. IT CANNOT BE MOVED, WHICH IS THE POINT",
};

/** The eleven, in build order. */
export const BUILDABLE: readonly string[] = RECIPES.map((r) => r.group);
